# Auditoría del experimento: Sentiment140
Reconstruye desde el MLflow Tracking Server (sin copias locales) el protocolo, los runs, las ablaciones, las contribuciones y la cadena `sentiment140@champion` → run final → run experimental seleccionado.

In [1]:
import os, json, numpy as np, pandas as pd, mlflow
from IPython.display import display
from mlflow.tracking import MlflowClient
URI = os.environ.get("MLFLOW_TRACKING_URI", "http://34.230.57.243:5000")
mlflow.set_tracking_uri(URI); c = MlflowClient()
exp = c.get_experiment_by_name("nlp-lab2-sentiment140")
runs = [r for r in c.search_runs([exp.experiment_id], max_results=1000) if r.data.tags.get("lab_run_type")]
print(URI, "|", exp.name, exp.lifecycle_stage, "| mlflow", mlflow.__version__)
print(pd.Series([r.data.tags["lab_run_type"] for r in runs]).value_counts().to_dict())
def dl(rid, p): return mlflow.artifacts.download_artifacts(run_id=rid, artifact_path=p)

/home/ec2-user/SageMaker/lab2/envs/lab2/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

http://34.230.57.243:5000 | nlp-lab2-sentiment140 active | mlflow 3.17.0
{'experiment': 15, 'final': 1, 'protocol': 1}

## 1. Protocolo

In [2]:
prot = [r for r in runs if r.data.tags["lab_run_type"] == "protocol"]
assert len(prot) == 1, "debe existir exactamente un protocolo"
pid = prot[0].info.run_id
print("protocol_run_id:", pid); print(json.dumps(prot[0].data.params, indent=1))
parts = pd.read_csv(dl(pid, "protocol/partitions.csv"))
print("partitions:", len(parts), "filas | índices únicos:", parts["index"].is_unique,
      "| ascendente:", parts["index"].is_monotonic_increasing, "| folds:", parts["fold"].value_counts().sort_index().to_dict())
display(pd.read_csv(dl(pid, "protocol/members.csv")))

protocol_run_id: 99482e00b9c94bdc9755afde981c331e
{
 "dataset_id": "adilbekovich/Sentiment140Twitter",
 "dataset_revision": "b6037e127257d95b9b23d31f78b264b9ebe697fd",
 "sampling_strategy": "stratified",
 "sample_size": "200000",
 "random_seed": "42",
 "cv_strategy": "StratifiedKFold",
 "cv_folds": "3",
 "cv_shuffle": "true"
}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00,  4.75it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00,  4.75it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00,  4.69it/s]

partitions: 200000 filas | índices únicos: True | ascendente: True | folds: {0: 66667, 1: 66667, 2: 66666}

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 17.69it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 16.93it/s]

  member_id                                       notebook_arn
0       E01  arn:aws:sagemaker:us-east-1:<ACCOUNT>:noteb...

## 2. Runs experimentales y consistencia aritmética de las métricas

In [3]:
rows = []
for r in runs:
    t, m = r.data.tags, r.data.metrics
    if t["lab_run_type"] != "experiment": continue
    f = [m[f"macro_f1_fold_{i}"] for i in range(3)]
    rows.append(dict(experimento=t["lab_experiment_id"], etapa=t["lab_stage"], miembro=t["lab_member_id"],
                     config=t["lab_configuration_id"], run=r.info.run_id[:8], fold0=f[0], fold1=f[1], fold2=f[2],
                     media=m["macro_f1_mean"], std=m["macro_f1_std"],
                     media_ok=abs(np.mean(f) - m["macro_f1_mean"]) < 1e-6,
                     std_poblacional_ok=abs(np.std(f, ddof=0) - m["macro_f1_std"]) < 1e-6,
                     protocolo_ok=t["lab_protocol_run_id"] == pid))
df = pd.DataFrame(rows).sort_values(["etapa", "media"], ascending=[True, False])
display(df.round(5)); print("todas las métricas consistentes:", bool(df[["media_ok", "std_poblacional_ok", "protocolo_ok"]].all().all()))

,experimento,etapa,miembro,config,run,fold0,fold1,fold2,media,std,media_ok,std_poblacional_ok,protocolo_ok
0,ABLATION,ablation,E01,CFG_B0,76f7071f,0.78248,0.78075,0.78277,0.78200,0.00089,True,True,True
13,B0,baseline,E01,CFG_B0,03e4eb1c,0.78248,0.78075,0.78277,0.78200,0.00089,True,True,True
3,C_LOGREG,classifier,E01,CFG_R_TFIDF_UNI_BI,4b34cf05,0.79935,0.79975,0.80027,0.79979,0.00038,True,True,True
2,C_LINEAR_SVM,classifier,E01,CFG_C_LINEAR_SVM,ba8c13b4,0.79706,0.79615,0.79797,0.79706,0.00074,True,True,True
1,C_SGD,classifier,E01,CFG_C_SGD,9819d8cd,0.77922,0.78016,0.78074,0.78004,0.00063,True,True,True
9,P_ELONGATION,preprocessing,E01,CFG_P_ELONGATION,c1115730,0.78255,0.78173,0.78307,0.78245,0.00055,True,True,True
8,P_EMOJI,preprocessing,E01,CFG_P_EMOJI,dca0d382,0.78210,0.78051,0.78235,0.78165,0.00082,True,True,True
10,P_LEMMA,preprocessing,E01,CFG_P_LEMMA,d517b957,0.78046,0.77677,0.77947,0.77890,0.00156,True,True,True
11,P_STOPWORDS_NEGATION,preprocessing,E01,CFG_P_STOPWORDS_NEGATION,33f423d0,0.76822,0.76686,0.76752,0.76753,0.00055,True,True,True
12,P_STOPWORDS,preprocessing,E01,CFG_P_STOPWORDS,6b12c3dc,0.76019,0.75662,0.75817,0.75833,0.00146,True,True,True
14,T0,reference,E01,CFG_T0,ec33e9da,0.33338,0.33338,0.33337,0.33338,0.00000,True,True,True
5,R_TFIDF_UNI_BI,representation,E01,CFG_R_TFIDF_UNI_BI,0cc7f8b5,0.79935,0.79975,0.80027,0.79979,0.00038,True,True,True
6,R_TFIDF_UNI,representation,E01,CFG_R_TFIDF_UNI,629ee090,0.78820,0.78766,0.78814,0.78800,0.00024,True,True,True
7,R_BOW,representation,E01,CFG_B0,b3687e9a,0.78248,0.78075,0.78277,0.78200,0.00089,True,True,True
4,R_SPACY,representation,E01,CFG_R_SPACY,fc7607d9,0.68555,0.68743,0.68721,0.68673,0.00084,True,True,True

todas las métricas consistentes: True

## 3. Qué cambia cada configuración frente a B0

In [4]:
def flat(d, p=""):
    o = {}
    for k, v in (d or {}).items():
        if isinstance(v, dict) and v: o.update(flat(v, p + k + "."))
        else: o[p + k] = v
    return o
cfgs = {r.data.tags["lab_experiment_id"]: json.load(open(dl(r.info.run_id, "run/configuration.json")))
        for r in runs if r.data.tags["lab_run_type"] == "experiment"}
fb = flat(cfgs["B0"])
for k, cfg in cfgs.items():
    if k in ("T0", "B0"): continue
    fc = flat(cfg)
    print(f"{k:22}", sorted(x for x in set(fb) | set(fc) if fb.get(x) != fc.get(x) and not x.startswith("preprocessing.resources")))

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.92it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.51it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00,  9.81it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00,  9.81it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00,  9.53it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.21it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.84it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 17.32it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 17.08it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.04it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.73it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.17it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.86it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.91it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.50it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.66it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 16.68it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 16.38it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 17.31it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 16.68it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.95it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]

ABLATION               []
C_SGD                  ['classifier.parameters', 'classifier.parameters.random_state', 'classifier.type', 'representation.ngram_range', 'representation.type']
C_LINEAR_SVM           ['classifier.type', 'representation.ngram_range', 'representation.type']
C_LOGREG               ['representation.ngram_range', 'representation.type']
R_SPACY                ['representation.library', 'representation.library_version', 'representation.ngram_range', 'representation.parameters', 'representation.parameters.document_vector_method', 'representation.spacy_model', 'representation.spacy_model_version', 'representation.type']
R_TFIDF_UNI_BI         ['representation.ngram_range', 'representation.type']
R_TFIDF_UNI            ['representation.type']
R_BOW                  []
P_EMOJI                ['preprocessing.emoji', 'preprocessing.emoji_spec']
P_ELONGATION           ['preprocessing.elongation', 'preprocessing.elongation_spec']
P_LEMMA                ['preprocessing.lemmatize']
P_STOPWORDS_NEGATION   ['preprocessing.negators', 'preprocessing.stopwords']
P_STOPWORDS            ['preprocessing.stopwords']

## 4. Ablación

In [5]:
by = {r.data.tags.get("lab_experiment_id"): r for r in runs if r.data.tags["lab_run_type"] == "experiment"}
a = by["ABLATION"]; par = c.get_run(a.data.tags["lab_ablation_parent_run_id"])
print("decisión revertida:", a.data.params["ablation_reverted_decision"])
print("padre (candidato):", par.info.run_id, par.data.tags["lab_experiment_id"], "| config", par.data.tags["lab_configuration_id"])
d = par.data.metrics["macro_f1_mean"] - a.data.metrics["macro_f1_mean"]
print(f"media padre {par.data.metrics['macro_f1_mean']:.5f} - media ablación {a.data.metrics['macro_f1_mean']:.5f} = {d:.6f}",
      "| registrado:", round(a.data.metrics["macro_f1_delta"], 6), "| coincide:", abs(d - a.data.metrics["macro_f1_delta"]) < 1e-6)

decisión revertida: representation
padre (candidato): 4b34cf05ac4041978fa0cc28efc95f4c C_LOGREG | config CFG_R_TFIDF_UNI_BI
media padre 0.79979 - media ablación 0.78200 = 0.017786 | registrado: 0.017786 | coincide: True

## 5. Contribuciones por integrante

In [6]:
contrib = df[~df["experimento"].isin(["T0", "B0"])].groupby("miembro").agg(
    runs=("run", "count"), configuraciones=("config", "nunique"), etapas=("etapa", lambda s: sorted(set(s))))
contrib["cumple_minimo"] = (contrib["configuraciones"] >= 3) & (contrib["etapas"].map(len) >= 2)
display(contrib)

,runs,configuraciones,etapas,cumple_minimo
miembro,,,,
E01,13,11,"[ablation, classifier, preprocessing, represen...",True

## 6. Cadena de trazabilidad: alias → run final → run experimental seleccionado

In [7]:
mv = c.get_model_version_by_alias("sentiment140", "champion")
fin = c.get_run(mv.run_id); ft = fin.data.tags
sel = c.get_run(ft["lab_selected_experiment_run_id"])
cf = json.load(open(dl(fin.info.run_id, "run/configuration.json"))); cs = json.load(open(dl(sel.info.run_id, "run/configuration.json")))
print("sentiment140@champion -> versión", mv.version, "-> run final", fin.info.run_id, "-> experimental", sel.info.run_id, f"({sel.data.tags['lab_experiment_id']})")
print("tipo de run:", ft["lab_run_type"], "| estado:", fin.info.status, "| training_size:", fin.data.params["training_size"], "| test_macro_f1:", fin.data.metrics["test_macro_f1"])
print("mismo configuration_id:", ft["lab_configuration_id"] == sel.data.tags["lab_configuration_id"], "| configuraciones equivalentes:", cf == cs)
print("run de protocolo referenciado es el único:", ft["lab_protocol_run_id"] == pid)
print("artefactos del run final:", sorted(x.path for x in c.list_artifacts(fin.info.run_id) if x.path != "model") + ["+ model/"])
prov = json.load(open(dl(fin.info.run_id, "provenance/sagemaker-resource-metadata.json")))
print("ResourceArn == notebook_arn:", prov["ResourceArn"] == ft["notebook_arn"], "|", ft["notebook_arn"])

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 17.00it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 16.58it/s]

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.19it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.57it/s]

sentiment140@champion -> versión 1 -> run final a6bb89d7fd4d4657946bc1cbadf605bc -> experimental 4b34cf05ac4041978fa0cc28efc95f4c (C_LOGREG)
tipo de run: final | estado: FINISHED | training_size: 1360000 | test_macro_f1: 0.8255187213071261
mismo configuration_id: True | configuraciones equivalentes: True
run de protocolo referenciado es el único: True
artefactos del run final: ['provenance', 'reports', 'run', '+ model/']

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]

Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 18.86it/s]

ResourceArn == notebook_arn: True | arn:aws:sagemaker:us-east-1:<ACCOUNT>:notebook-instance/nlp-lab2-cardona

## 7. API desplegada (opcional)
Compara lo que responde la API con lo que muestra MLflow.

In [8]:
import requests
API = os.environ.get("API_URL", "http://34.230.57.243:8000")
try:
    h = requests.get(API + "/health", timeout=10).json(); m = requests.get(API + "/audit/model", timeout=60).json()
    p = requests.post(API + "/api/v1/predict", json={"text": ["i loved it", "worst day ever"]}, timeout=30).json()
    print(h, "\n", p, "\n audit/model run_id:", m["run_id"], "| coincide con el alias:", m["run_id"] == mv.run_id == h["model_run_id"] == p["model_run_id"])
except Exception as e:
    print("API no disponible:", e)

{'status': 'ok', 'model_run_id': 'a6bb89d7fd4d4657946bc1cbadf605bc'}
 {'model_run_id': 'a6bb89d7fd4d4657946bc1cbadf605bc', 'predictions': ['positive', 'negative']}
 audit/model run_id: a6bb89d7fd4d4657946bc1cbadf605bc | coincide con el alias: True